Numpy


In [1]:
# Numpy is the fundamental package for scientific computing in Python.
# NumPy is a python library that provides a multidimensional array object, various derived objects.

What is NumPy Array ?

In [3]:
#An array is a grid of values and it contains information about the raw data , how to locate an element , 
#how to interpret an element.

 Advantages of Numpy vs python list

In [4]:
 # consumes less memory 
# fast as compared to the python list
# convenient to use

In [9]:
import numpy as np
x = np.array([1,2,3,4])
print (x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
 y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


Numpy Array vs List

In [11]:
# data types storage
# importing module # package of numpy should be installed and import
# Numerical Operation
# Modification capabitlites
#consumes less memory
# Fast as compared to the Python list
# convenient to use

How to create Numpy Array

In [12]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)

[1 2 3 4]


In [19]:
l = []
for i in range (1,5):
     data = int(input("Enter the data:"))
     l.append(data)
print(np.array(l))

Enter the data: 11
Enter the data: 12
Enter the data: 13
Enter the data: 14


[11 12 13 14]


Dimensions in Array

In [20]:
import numpy as np
x = [1,2,3,4]
y = np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [21]:
ar2 = np.array([[1,2,3,4]])
print (ar2)
print(ar2.ndim)

[[1 2 3 4]]
2


In [22]:
ar3 = np.array([[[1,2,3,4]]])
print (ar3)
print(ar3.ndim)

[[[1 2 3 4]]]
3


In [23]:
arn = np.array([1,2,3,4], ndmin = 10)
print (arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


How to create Numpy Array using Numpy Function

Zeros

In [27]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 =np.zeros((3,4))
print(ar_zero1)
print()
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0. 0. 0. 0.]


Ones

In [29]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


Empty array

In [30]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


Range

In [31]:
ar_range = np.arange(4)
print(ar_range)

[0 1 2 3]


Array diagonal element with 1

In [32]:
ar_dia = np.eye(3)
print (ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
ar_dia = np.eye(3,5)
print (ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [34]:
ar_dia = np.eye(4,4) # Identity Matrix
print (ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


linspace

In [40]:
ar_lin = np.linspace(0,20, num =5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


How to create Numpy Arrays with Random Numbers

In [41]:
 #rand() : The function is used to generate a random value between 0 to 1
#randn () : the function  is used to generate a random value close to zero.
             #This may return positive or negative numbers as well.

Random

rand()

In [43]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.98121028 0.5794416  0.57375109 0.20337064]


In [44]:
import numpy as np
var1 = np.random.rand(2,5)
print(var1)

[[0.175579   0.11247947 0.57118303 0.72054716 0.33955226]
 [0.34581405 0.5919939  0.43797519 0.85635592 0.39537577]]


randn()

In [45]:
var2 = np.random.randn(5)
print(var2)

[ 0.95453253  2.07535817 -0.45313196  0.9732653   0.52137774]


ranf()

In [46]:
# ranf() is the function for doing random sampling in numpy . It returns an array of specified shape and
# fills it with random floats in the half open interval [0.0  , 1,0)

In [47]:
var3 = np.random.ranf(4)
print(var3)

[0.84756537 0.68624051 0.59054328 0.32781834]


randint()

In [48]:
#rand() : The function is used to generate a random number between a given range.

In [50]:
var4 =np.random.randint(5,20,5)  # (min, max, total values)
print(var4)

[13 18 16  5  8]


What is data type in numpy array ?

In [51]:
import numpy as np
var= np.array([1,2,3,4])
print ("Data Type : ", var.dtype)

Data Type :  int32


In [52]:
import numpy as np
var= np.array([1.2,3,2.4,3.4,4.5])
print ("Data Type : ", var.dtype)

Data Type :  float64


In [1]:
x =np.array([1,2,3,4])

NameError: name 'np' is not defined

What are arithmetic operators

In [3]:
# Add
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print (varadd)

[4 5 6 7]


In [4]:
var1 = np.array([1,2,3,4])
var2 =np .array([1,2,3,4])
varadd = var1 + var2
print (varadd)

[2 4 6 8]


In [5]:
var = np.array([1,2,3,4])
varadd = var - 3
print (varadd)

[-2 -1  0  1]


In [6]:
var = np.array([1,2,3,4])
varadd = var * 3
print (varadd)

[ 3  6  9 12]


In [7]:
var = np.array([1,2,3,4])
varadd = var % 3
print (varadd)

[1 2 0 1]


In [8]:
var1 = np.array([1,2,3,4])
var2 =np .array([1,2,3,4])
varadd = np.add(var1, var2)
print(varadd)

[2 4 6 8]


2D Array

In [13]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array ([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()

print()
varadd2 = var21 + var22
print(varadd2)



[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]


[[2 4 6 8]
 [2 4 6 8]]


Arithmetic functions in numpy

In [14]:
# np.min(x)
#np.max(x)
#np.argmin(x)
#np.sqrt(x)
#np.sin(x)
#np.cos(x)
#np.cumsum(x)  # Cummulative Sum

In [17]:
import numpy as np
var = np.array ([1,2,3,4,5,3,2])
print("min : " ,np.min(var))

min :  1


In [18]:
var = np.array ([1,2,3,4,5,3,2])
print("max : " ,np.max(var))

max :  5


In [19]:
var = np.array ([1,2,3,4,5,3,2])
print("Position of max : " ,np.argmax(var))

Position of max :  4


In [20]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis = 1))
print("Position of min : " ,np.argmin(var))

Position of min :  0


In [22]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis = 1)) # row

[1 5]


In [23]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis = 0)) # column

[2 1 3]


In [24]:
var = np.array ([1,2,3,4,5,3,2])
print("sqrt : " ,np.sqrt(var))

sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [31]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
var = np.array([1,2,3,4,5,6,7])
print(np.cumsum(var))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1  3  6 10 15 21 28]


Shape and Reshape in Numpy Arrays

Shape

In [33]:
import numpy as np
var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [36]:
var1 = np.array([1,2,3,4],ndmin =4)
print (var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


Reshape

In [39]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()
x= var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [42]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x= var3.reshape(2,3,2)
print(x)
print(x.ndim)
print()
one = x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


Broadcasting array in numpy

In [44]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print(var1 + var2)

[2 4 6 8]


In [48]:
import numpy as np
var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()
var2 = np.array([[1],[2],[3]])
print(var2)
print()
print(var2.shape)
print()
print(var1+var2)

(3,)

[1 2 3]

[[1]
 [2]
 [3]]

(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [50]:
x =np.array([[1],[2]])
print(x.shape)
y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()
print(x+y)


(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


Creating an Array

In [2]:
import numpy as np
x =np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# WE cam also pass list, tuple or any array like an object with array() and it will be converted to ndarray

In [6]:
import numpy as np
x = np.array((1,2,3,4,5))
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


 Dimensions in arrays

In [7]:
 # 0 array


In [8]:
import numpy as np
x = np.array(42)
print(x)

42


In [9]:
# 1 D array

In [10]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [11]:
# 2-D array

In [12]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [13]:
# Now we will create with 2-D array.

In [15]:
import numpy as np
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
# check how many dimensions the array have : ndim() attribute

In [19]:
import numpy as np
x = np.array(42)
y = np.array([1,2,3,4,5])
z = np.array([[1,2,3],[4,5,6]])
print(x.ndim)
print(y.ndim)
print(z.ndim)

0
1
2


 Indexing an array element

In [23]:
import numpy as np
x = np.array([1,2,3,4])
print(x[-1])


4


In [25]:
import numpy as np
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Fifth Element in the second rows :",x[1,4])

Second Element in the 1St rows : 10


In [26]:
# Accessing the 3-D 

In [27]:
import numpy as np
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x[0,1,2])


6


Numpy Array Slicing

In [38]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9])
print(x[1:5])
print(x[4:])
print(x[:])
print(x[:4])
print(x[:-1])
print (x[-6:-1])

[2 3 4 5]
[5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[1 2 3 4 5 6 7 8]
[4 5 6 7 8]


In [39]:
# step

In [42]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9])
print (x[::2])

[1 3 5 7 9]


Slicing 2-D Array

In [47]:
import numpy as np
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (x[1,1:4])
print(x[0:2,2])

[7 8 9]
[3 8]


In [48]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [52]:
#np.ones and np.zeros
np.ones((3,4))
print()
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
#np.random
np.random.random((3,4))

array([[0.61254439, 0.80242287, 0.30852595, 0.67414184],
       [0.29146813, 0.50980249, 0.30275079, 0.73994459],
       [0.27999127, 0.69706563, 0.19154454, 0.36326382]])

In [54]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [57]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Indexing and slicing 

In [4]:
import numpy as np
a1 = np.arange(10)
print(a1)
print()
a2 = np.arange(12).reshape(3,4)
print(a2)
print()
a3 =np.arange(8).reshape(2,2,2)
print(a3)
print()

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [5]:
a2[1,2]

6

In [6]:
a2[2,3]

11

In [7]:
a2[1,0]

4

In [8]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
a2[2,2]

10

In [10]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [11]:
a3[1,0,1]

5

In [12]:
a3[1,1,0]

6

In [13]:
a3[0,1,0]

2

In [14]:
a3[0,0,0]

0

Slicing

In [15]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
a1[2:5]

array([2, 3, 4])

In [17]:
a1[2:5:2]

array([2, 4])

In [18]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
a2[0,:]

array([0, 1, 2, 3])

In [20]:
a2[:,2]

array([ 2,  6, 10])

In [21]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [22]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [23]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [26]:
a2[1:,3]

array([ 7, 11])

In [27]:
a2[1,::3]

array([4, 7])

In [28]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [30]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [31]:
a3 = np.arange(27).reshape(3,3,3)

In [32]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [33]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [34]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
a3[0,1,:]

array([3, 4, 5])

In [36]:
a3[1,:,1]

array([10, 13, 16])

In [37]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [40]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [41]:
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [42]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Indexing and Slicing

In [44]:
import numpy as np
var = np.array([9,8,7,6])
var[:]

array([9, 8, 7, 6])

In [45]:
var[-1]

6

In [46]:
var[1:]

array([8, 7, 6])

In [47]:
var[::2]

array([9, 7])

In [48]:
var[::3]

array([9, 6])

2-D Array

In [50]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)

[[9 8 7]
 [4 5 6]]
2


In [53]:
var1[0,1]

8

In [54]:
var1[1,0]

4

In [56]:
var1[1,2]

6

In [58]:
var1[1,2]

6

In [59]:
print(var1)

[[9 8 7]
 [4 5 6]]


In [60]:
var1[1,1]

5

In [64]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print()

                

[[[1 2]
  [6 7]]]
3



In [67]:
var2[0,1,1]

7

In [68]:
var2[0,0,1]

2

In [69]:
var2[0,0,0]

1

Slicing

In [70]:
import numpy as np
var =np.array([1,2,3,4,5,6,7])
print(var)

[1 2 3 4 5 6 7]


In [71]:
var[1:4]

array([2, 3, 4])

In [73]:
var[4:]

array([5, 6, 7])

In [74]:
var[0::2]

array([1, 3, 5, 7])

In [75]:
print(var)

[1 2 3 4 5 6 7]


In [76]:
var[3:6]

array([4, 5, 6])

2-D array

In [77]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)



[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]


In [78]:
var1[1,1:]

array([8, 7, 6, 5])

In [4]:
import numpy as np
a1=  np.arange(10)
print(a1)
for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [5]:
a2 = np.arange(12).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
a3 =np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [7]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [9]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [10]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7


Transpose

NameError: name 'np' is not defined

In [2]:
import numpy as np
a1=  np.arange(10)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.transpose(a1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a2 = np.arange(12).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [8]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Ravel

In [10]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a3 =np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

Stacking

In [14]:
# Horizontal Stacking

In [16]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [19]:
#vertical stacking

In [20]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Iterating Numpy Arrays

In [21]:
import numpy as np
var = np.array([9,8,7,6,5,4])
print(var)
for i in var:
    print(i)
    

[9 8 7 6 5 4]
9
8
7
6
5
4


In [25]:
var1 =np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
for i in var1:
    print(i)
print()
for j in var1:
    for  in j:
        print(j)

[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[1 2 3 4]

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [28]:
var3= np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i in var3:
    for j in i:
        for k in j:
            print(k)
            

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


nditer()

In [30]:
var3= np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i in np.nditer(var3,flags = ['buffered'],op_dtypes= ['S']):
    print(i)
   

[[[1 2 3 4]
  [1 2 3 4]]]
3

b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [33]:
#ndenumerate () Prints the index value
var3= np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i,d in np.ndenumerate(var3):
    print(i,d)
   

[[[1 2 3 4]
  [1 2 3 4]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [35]:
import numpy as np
x = np.array([1,2,3])
for i in x:
    print(i)

1
2
3


In [36]:
#2-D

In [42]:
import numpy as np
y = np.array([[1,2,3],[4,5,6]])
for i in y:
    for a in i:
        print(a)
    

1
2
3
4
5
6


In [39]:
#3-D

In [41]:
import numpy as np
z = np.array([[[1,2,3],[4,5,6],[10,11,12]]])
for i in z:
    for a in i:
        for b in a:
            print(b)
    

1
2
3
4
5
6
10
11
12


In [43]:
#nditer()

In [44]:
import numpy as np
x = np.array([[[1,2],[3,4],[5,6],[7,8]]])
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8


Stacking

In [48]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1)
print()
print(arr2)

[1 2 3 4]

[5 6 7 8]


In [49]:
np.hstack((arr1,arr2)) # Horizontally Arranges the matrix

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.vstack((arr1,arr2)) # Vertically Arranges the matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Numpy Array vs Python List

Advanced Indexing

In [2]:
#Noramal Indexing and Slicing
import numpy as np
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
a[1,2]

5

In [4]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

Fancy Indexing

In [5]:
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [6]:
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a = np.arange(24).reshape(6,4)

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [11]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [12]:
# Boolean Indexing

In [13]:
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[61, 14, 64, 99],
       [60, 18,  8, 39],
       [52, 68, 60, 66],
       [42, 22, 79, 47],
       [92, 48, 41, 88],
       [96, 48, 30, 20]])

In [14]:
# Find all numbers greater than 50

In [15]:
a > 50

array([[ True, False,  True,  True],
       [ True, False, False, False],
       [ True,  True,  True,  True],
       [False, False,  True, False],
       [ True, False, False,  True],
       [ True, False, False, False]])

In [16]:
a[a>50]

array([61, 64, 99, 60, 52, 68, 60, 66, 79, 92, 88, 96])

In [18]:
# Find out even numbers

In [19]:
a% 2 == 0

array([[False,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [20]:
a[a % 2==0]

array([14, 64, 60, 18,  8, 52, 68, 60, 66, 42, 22, 92, 48, 88, 96, 48, 30,
       20])

In [21]:
# Find all numbers greater than 50 and are even

In [22]:
(a>50) & (a%2==0)

array([[False, False,  True, False],
       [ True, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False,  True],
       [ True, False, False, False]])

In [24]:
a[(a>50) & (a % 2== 0)]

array([64, 60, 52, 68, 60, 66, 92, 88, 96])

In [25]:
#Find all numbers  divisbile by 7

In [28]:
a[a%7==0]

array([14, 42])

Broadcasting

In [29]:
#The term broadcasting describes how NumPy treats array with different shapes during arithmetic operations
# The smaller array is "broadcast" across the larger array so that they have compatible shapes.

In [33]:
#same shape
a =np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print()
print(b)
print()
print(a+b)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]

[[ 6  8 10]
 [12 14 16]]


In [35]:
a =np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print()
print(b)
print()
print(a+b)

[[0 1 2]
 [3 4 5]]

[[0 1 2]]

[[0 2 4]
 [3 5 7]]


Broadcasting Rules

In [36]:
# 1. Make the two arrays have the same number of dimensions.
#  -> If the number of dimensions of the two arrays are different , add new dimensions with size 1 
#      the head of the array with the smaller dimension.

In [37]:
# 2. Make each dimension of the two arrays the same size.
# ->  If the sizes of each dimension of the two arrays do not match,dimesions with size 1
#     are stretched to the size of the other array.
# ->  If there is a dimension whose size is not 1 in either of the two arrays, it cannot be
#     be broadcasted , and an error is raised.

In [38]:
# More Examples


In [40]:
a = np.arange(12).reshape(4,3)
b =np.arange(3)
print(a)
print()
print(b)
print()
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [41]:
a = np.arange(12).reshape(3,4)
b =np.arange(3)
print(a)
print()
print(b)
print()
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2]



ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [42]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print()
print(b)
print()
print(a+b)

[[0 1 2]]

[[0]
 [1]
 [2]]

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [44]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
print(a)
print()
print(b)
print()
print(a+b)

[[0 1 2]]

[[0]
 [1]
 [2]
 [3]]

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [45]:
 a= np.array([1])
# shape -> (1,1)
b =np.arange(4).reshape(2,2)
# shape -> (2,2)
print(a)
print()
print(b)
print()
print(a+b)

[1]

[[0 1]
 [2 3]]

[[1 2]
 [3 4]]


In [46]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
print(a)
print()
print(b)
print()
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [47]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
print(a)
print()
print(b)
print()
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1]
 [2 3]]



ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 